#!/bin/bash
../bin/ecs-docker-run \
  --generate-only \
  --cluster my-own-cluster \
  --number-of-instances 3 \
  --memory 256 \
  --cpu-shares 512 \
  --entrypoint new-entry-point \
  --rm \
  --name app-hellodb \
  --env SERVICE_NAME=hellodb \
  --env SERVICE_TAGS=http \
  --env "MESSAGE=Hello World" \
  --link a:a \
  --link b:b \
  -v /host/path:/container/path \
  --volumes-from container-a \
  --volumes-from container-b \
  -p :1000:100 \
  -p :1001:101/udp \
  -p :1002:102/tcp \
  cargonauts/helloworld-python \
  /srv/helloworld-db.py	 \
  | jq . > output/$(basename $0).json


diff {output,expect}/$(basename $0).json 
[ $? -ne 0 ] && echo ERROR: test $(basename $0) failed || echo INFO: test $(basename $0)  succeeded


